# findCOMStrategy.R
# This function executes a portfolio strategy that uses the list of 
# portfolios generated by the COMLongShortPortfolios.R script. It is 
# identical in function to findDailyStrategy.m (Matlab)

FindComStrategy = function(numHoldingDays, numLongShort, xtsPrice, xtsCOM, 
                           industryData, daysToWait) {
  
  #Load packages and source files
  library(xts)
  #library(xlsx)
  source('~/R/AdamReed/BuildLongShortPortfolio.R')
  source('~/R/AdamReed/COMLongShortStocks.R')
  source('~/R/AdamReed/PickLHstocks.R')
  source('~/R/AdamReed/HoldPortfolio.R')
  
  
  LongShort <- COMLongShortStocks(numHoldingDays, numLongShort, xtsPrice, xtsCOM,
                                  industryData, daysToWait)
  xtsLongStocks <- LongShort$long
  xtsShortStocks <- LongShort$short  

  # Prepopulate xts object to be filled
  priceDates <- index(xtsLongStocks)
  COMDates <- (index(xtsCOM))
  xtsPortPrice <- xtsLongStocks[, 1]
  first <- as.Date(as.numeric(COMDates[1]) + daysToWait[1])
  last <- as.Date(as.numeric(COMDates[length(COMDates)]) + daysToWait[length(daysToWait)] + numHoldingDays)
  range <- paste(first, '::', last, sep='')
  xtsPortPrice <- xtsPortPrice[range]
  
  PortDollarValue <- 100000
  numPeriods <- length(COMDates)
  
  # Calculate portfolio returns
  for (i in 1:numPeriods) { 
    first <- as.Date(as.numeric(COMDates[i]) + daysToWait[i])
    if(i == length(COMDates)) {
      last <- as.Date(as.numeric(COMDates[length(COMDates)]) + 
                        numHoldingDays + daysToWait[i])
      # Last date of retDates
    } else {
      last <- as.Date(as.numeric(COMDates[i+1]) - 1 + daysToWait[i])
    } # End conditional statement
    
    range <- paste(first, '::', last, sep='')
    xtsLongTemp <- xtsLongStocks[range]
    xtsShortTemp <- xtsShortStocks[range]
    
    xtsLongTemp <- RemoveNAcolumns(xtsLongTemp)
    xtsShortTemp <- RemoveNAcolumns(xtsShortTemp) 
    wgtsLong <- rep(1/ncol(xtsLongTemp), ncol(xtsLongTemp))
    wgtsShort <- rep(-1/ncol(xtsShortTemp), ncol(xtsShortTemp))
    xtsLongShortTemp <- cbind(xtsLongTemp, xtsShortTemp)
    wgts <- c(wgtsLong, wgtsShort)
    
    xtsTempPortPrice <- HoldPortfolio(xtsLongShortTemp, wgts, 
                                      PortDollarValue)  + PortDollarValue
    xtsPortPrice[range] <- xtsTempPortPrice
    
    # Set new portfolio dollar value to last value of xtsTempPortPrice
    PortDollarValue <- as.numeric(xtsTempPortPrice[length(xtsTempPortPrice)])                
  } # End for loop

  return(xtsPortPrice)
}